<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [2]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    # write your code
    if len(A[0]) == len(B):
        resList = []
        for i in range(0, len(A)):
            locList = []
            for j in range(0, len(B[0])):
                total_sum = 0
                for k in range(0, len(A[0])):
                    total_sum += A[i][k] * B[k][j]
                locList.append(total_sum)
            resList.append(locList)
        return resList
    else:
        return "Not possible"

A = [[1, 2], [3, 4]]
B = [[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]
# A = [[1, 3, 4], [2, 5, 7], [5, 9, 6]]
# B = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
# A = [[1, 2], [3, 4]]
# B = [[1, 4], [5, 6],[7, 8], [9, 6]]
print(matrix_mul(A, B))

[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [111]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    random_number = round(uniform(1, 100))
    
    A_sum = sum(A)
    
    list1=[]
    for j in range(len(A)):
        list1.append(int(A[j])/int(A_sum))
        
    list2=[]
    list2.append(0)
    
    for k in range(len(A)):
        list2.append(list2[k] + list1[k])
    list2.pop(0)
    
    random_number = uniform(0.0,1.0)
    
    number = 0
    for idx in range(len(A)):
        if(random_number <= list2[idx]):
            number = A[idx]
            break
            
    return number

def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
sampling_based_on_magnitued()

79
27
100
79
79
100
100
100
79
45
27
28
45
79
79
79
100
100
100
45
45
100
79
13
79
13
100
27
100
45
79
100
79
100
45
79
79
100
79
6
79
100
100
45
79
28
45
100
13
45
6
100
79
13
27
45
79
45
79
79
5
6
28
79
13
10
45
79
100
79
100
10
45
27
100
100
79
27
100
28
13
79
79
100
27
28
79
45
45
28
79
100
79
79
5
10
100
79
27


<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [112]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    # 
    for char in String:
        if not (char >= '0' and char <= '9'):
            String = String.replace(char, '')
    for char in String:
        if (char >= '0' and char <= '9'):
            String = String.replace(char, '#')
            
    return(String) # modified string which is after replacing the # with digits

String = '#2a$#b%c%561#'
print(replace_digits(String))

####


<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [120]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    # write code for computing top top 5 students
    top_5_students = []
    for i in range(5):
        top_5_students.append(students[marks.index(sorted(marks, reverse=True)[:5][i])])
        
        
    # write code for computing top least 5 students
    least_5_students = []
    for i in range(5):
        least_5_students.append(students[marks.index(sorted(marks)[:5][i])])
        
        
    # write code for computing top least 5 students
    students_within_25_and_75 = []
    sorted_marks = sorted(marks)
    length = len(sorted_marks)
    for i in range(len(sorted_marks)):
        if sorted_marks[i] >= sorted_marks[int(length / 4)] and sorted_marks[i] < sorted_marks[int(3 * length / 4)]:
            students_within_25_and_75.append(students[marks.index(sorted(marks)[i])])
            
    
    return top_5_students, least_5_students, students_within_25_and_75


students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print(top_5_students,'\n', least_5_students, '\n', students_within_25_and_75)

['student8', 'student10', 'student2', 'student5', 'student7'] 
 ['student3', 'student4', 'student9', 'student6', 'student1'] 
 ['student9', 'student6', 'student1', 'student7', 'student5']


<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [2]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    S.sort(key=lambda i: math.sqrt((float(i[0]) - P[0]) ** 2 + (float(i[1]) - P[1]) ** 2))
    return S[:5]

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print(points) #print the returned values

[(1, -1), (6, -7), (-1, -1), (6, 0), (1, 2)]


<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [77]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    
    x = y = z = 0
    line_list = []
    
    if '+' in line and not '-' in line:
        line_list = line.split("+")
        x = float(''.join(i for i in line_list[0] if i.isdigit()))
        y = float(''.join(i for i in line_list[1] if i.isdigit()))
        z = float(''.join(i for i in line_list[2] if i.isdigit()))
    elif '-' in line and not '+' in line:
        line_list = line.split("-")
        x = float(''.join(i for i in line_list[0] if i.isdigit()))
        y = float(''.join(i for i in line_list[1] if i.isdigit()))
        z = float(''.join(i for i in line_list[2] if i.isdigit()))
    elif '+' in line and '-' in line:
        list1 = line.split("+")
        for i in range(len(list1)): 
            if '-' in list1[i] and i == 0:
                x1 = list1[i].split('-')
                x = float(''.join(j for j in x1[0] if j.isdigit()))
                y = float(''.join(j for j in x1[1] if j.isdigit()))
                y = -y
                z = float(list1[i+1])
                if z > 0:
                    z = -z
                break
                    
            else:
                if i == 0 and not '-' in list1[i]:
                    x = float(''.join(j for j in list1[i] if j.isdigit()))    
                elif '-' in list1[i] and i == 1:
                    x1 = list1[i].split('-')
                    y = float(''.join(j for j in x1[0] if j.isdigit()))
                    z = float(x1[1])
                    if z > 0 or z < 0:
                        z = -z
    
    # print(x, " ", y, " ", z)
                              
    flag1 = 0
    for itr in range(len(red)):
        res = float(x * red[itr][0]) + float(y * red[itr][1])
        if float(z) <= res:
            flag1 = 1
        else:
            flag1 = 0
            break
    
    flag2 = 0
    for itr in range(len(blue)):
        res = float(x * blue[itr][0]) + int(y * blue[itr][1])
        if float(z) > res:
            flag2 = 1
        else:
            flag2 = 0
            break
            
            
    if flag1 == 1 and flag2 == 1:
        return "YES"
    else:
        return "NO"


Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [121]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    list1 = string.split(",")

    idx = prev_idx = prev_val = current_val = 0
    
    while idx < len(list1):
        if list1[idx] != '_' or idx+1 == len(list1):
            value = 0
            if list1[idx] != '_':
                value = int((int(list1[idx]) + prev_val) / (idx - prev_idx + 1))
            elif value == 0:
                value = int(prev_val / (idx - prev_idx + 1))
                
            while prev_idx <= idx:
                list1[prev_idx] = value
                prev_idx += 1
                
            prev_idx -= 1 
            prev_val = value
              
        idx += 1
        
    return list1


S = ["_,_,_,24", "40,_,_,_,60", "80,_,_,_,_", "_,_,30,_,_,_,50,_,_"]
for i in range(len(S)):
    smoothed_values= curve_smoothing(S[i])
    print(smoothed_values)

[6, 6, 6, 6]
[20, 20, 20, 20, 20]
[16, 16, 16, 16, 16]
[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [114]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    # print the output as per the instructions
    
    dict1 = {'F1S1': 0, 'F2S1': 0, 'F3S1': 0, 'F4S1': 0, 'F5S1': 0,
             'F1S2': 0, 'F2S2': 0, 'F3S2': 0, 'F4S2': 0, 'F5S2': 0,
             'F1S3': 0, 'F2S3': 0, 'F3S3': 0, 'F4S3': 0, 'F5S3': 0}

    dict2 = {'S1': 0, 'S2': 0, 'S3': 0}
    
    for idx in range(len(A)):
        first_idx = A[idx][0]
        second_idx = A[idx][1]
        dict1[first_idx + second_idx] += 1
        dict2[second_idx] += 1
    
    # print statements
    print("a. P(F=F1|S==S1)={}/{},".format(str(dict1['F1S1']),str(dict2['S1'])), "P(F=F1|S==S2)={}/{},".format(str(dict1['F1S2']),str(dict2['S2'])), "P(F=F1|S==S3)={}/{}".format(str(dict1['F1S3']),str(dict2['S3'])))
    print("b. P(F=F2|S==S1)={}/{},".format(str(dict1['F2S1']),str(dict2['S1'])), "P(F=F2|S==S2)={}/{},".format(str(dict1['F2S2']),str(dict2['S2'])), "P(F=F2|S==S3)={}/{}".format(str(dict1['F2S3']),str(dict2['S3'])))
    print("c. P(F=F3|S==S1)={}/{},".format(str(dict1['F3S1']),str(dict2['S1'])), "P(F=F3|S==S2)={}/{},".format(str(dict1['F3S2']),str(dict2['S2'])), "P(F=F3|S==S3)={}/{}".format(str(dict1['F3S3']),str(dict2['S3'])))
    print("d. P(F=F4|S==S1)={}/{},".format(str(dict1['F4S1']),str(dict2['S1'])), "P(F=F4|S==S2)={}/{},".format(str(dict1['F4S2']),str(dict2['S2'])), "P(F=F4|S==S3)={}/{}".format(str(dict1['F4S3']),str(dict2['S3'])))
    print("e. P(F=F5|S==S1)={}/{},".format(str(dict1['F5S1']),str(dict2['S1'])), "P(F=F5|S==S2)={}/{},".format(str(dict1['F5S2']),str(dict2['S2'])), "P(F=F5|S==S3)={}/{}".format(str(dict1['F5S3']),str(dict2['S3'])))

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
compute_conditional_probabilites(A)

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3


<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [115]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    list1 = S1.split(" ")
    list2 = S2.split(" ")

    a = set(list1)&set(list2)
    b = set(list1) - set(list2)
    c = list(set(list2) - set(list1))
    return len(a), sorted(b, key = lambda k : list1.index(k)), c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print("a. ", a)
print("b. ", b)
print("c. ", c)

a.  7
b.  ['first', 'F', '5']
c.  ['S', 'second', '3']


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [116]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    loss = 0
    for row in A:
        Y = int(row[0])
        Y_score = float(row[1])
        #print(Y, " * ", Y_score)
        loss += ((Y * math.log10(Y_score)) + ((1-Y) * math.log10(1-Y_score)))
        #print(loss)
    loss *= (-1/len(A))
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
