In [1]:
import numpy as np
a = np.arange(1,5)
b = np.arange(11,15)
a,b

(array([1, 2, 3, 4]), array([11, 12, 13, 14]))

In [4]:
a*b

array([11, 24, 39, 56])

In [5]:
a.T*b

array([11, 24, 39, 56])

In [6]:
np.dot(a,b)

130

# <font color='red'><b>Bootstrap assignment</b> </font>

<b>There will be some functions that start with the word "grader" ex: grader_sampples(), grader_30().. etc, you should not change those function definition.

Every Grader function has to return True.</b>

<font color='blue'> <b>Importing packages</b> </font>

In [1]:
import numpy as np # importing numpy for numerical computation
from sklearn.datasets import load_boston # here we are using sklearn's boston dataset
from sklearn.metrics import mean_squared_error # importing mean_squared_error metric

In [2]:
boston = load_boston()
x=boston.data #independent variables
y=boston.target #target variable

In [3]:
x.shape

(506, 13)

In [4]:
x[:5]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01,
        6.5750e+00, 6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02,
        1.5300e+01, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00],
       [3.2370e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        6.9980e+00, 4.5800e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9463e+02, 2.9400e+00],
       [6.9050e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        7.1470e+00, 5.4200e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9690e+02, 5.3300e+00]])

## <font color='red'><b>Task 1</b></font>

<font color='red'> <b>Step - 1</b></font>

*  <font color='blue'><b>Creating samples</b></font><br>
    <b> Randomly create 30 samples from the whole boston data points</b>
    *  Creating each sample: Consider any random 303(60% of 506) data points from whole data set and then replicate any 203 points from the sampled points
    
     For better understanding of this procedure lets check this examples, assume we have 10 data points [1,2,3,4,5,6,7,8,9,10], first we take 6 data points randomly , consider we have selected [4, 5, 7, 8, 9, 3] now we will replicate 4 points from [4, 5, 7, 8, 9, 3], consder they are [5, 8, 3,7] so our final sample will be [4, 5, 7, 8, 9, 3, 5, 8, 3,7]
* <font color='blue'><b> Create 30 samples </b></font>
    *  Note that as a part of the Bagging when you are taking the random samples <b>make sure each of the sample will have different set of columns</b><br>
Ex: Assume we have 10 columns[1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10] for the first sample we will select [3, 4, 5, 9, 1, 2] and for the second sample  [7, 9, 1, 4, 5, 6, 2] and so on...
Make sure each sample will have atleast 3 feautres/columns/attributes

<font color='red'><b>Step - 2 </b></font>

<font color='blue'><b>Building High Variance Models on each of the sample and finding train MSE value</b></font>

*  Build a regression trees on each of 30 samples.
*  Computed the predicted values of each data point(506 data points) in your corpus.
*  Predicted house price of $i^{th}$ data point $y^{i}_{pred} =  \frac{1}{30}\sum_{k=1}^{30}(\text{predicted value of } x^{i} \text{ with } k^{th} \text{ model})$
*  Now calculate the $MSE =  \frac{1}{506}\sum_{i=1}^{506}(y^{i} - y^{i}_{pred})^{2}$

<font color='red'> <b>Step - 3 </b></font>

*  <font color='blue'><b>Calculating the OOB score </b></font>

*  Predicted house price of $i^{th}$ data point $y^{i}_{pred} =  \frac{1}{k}\sum_{\text{k= model which was buit on samples not included } x^{i}}(\text{predicted value of } x^{i} \text{ with } k^{th} \text{ model})$.
*  Now calculate the $OOB Score =  \frac{1}{506}\sum_{i=1}^{506}(y^{i} - y^{i}_{pred})^{2}$.

# <font color='red'><b>Task 2</b></font>

*  <font color='blue'><b>Computing CI of OOB Score and Train MSE</b></font>
  *   Repeat Task 1 for 35 times, and for each iteration store the Train MSE and OOB score </li>
<li> After this we will have 35 Train MSE values and 35 OOB scores </li>
<li> using these 35 values (assume like a sample) find the confidence intravels of MSE and OOB Score </li>
<li> you need to report CI of MSE and CI of OOB Score </li>
<li> Note: Refer the Central_Limit_theorem.ipynb to check how to find the confidence intravel</li>
</ol>

# <font color='red'><b>Task 3</b></font>

*  <font color='blue'><b>Given a single query point predict the price of house.</b></font>

Consider xq= [0.18,20.0,5.00,0.0,0.421,5.60,72.2,7.95,7.0,30.0,19.1,372.13,18.60] 
Predict the house price for this point as mentioned in the step 2 of Task 1.

<br><br><br>

# <font color='blue'> <b>Task - 1</b></font>

<font color='blue'><b>Step - 1</b></font>

*  <font color='blue'> <b>Creating samples</b></font>

<font color='Orange'><b>Algorithm</b></font>

![alt text](https://i.imgur.com/BTVYXQ1.jpg/)

*  <font color='blue'><b> Write code for generating samples</b></font>

In [5]:
def generating_samples(input_data, target_data):

    '''In this function, we will write code for generating 30 samples '''
    # you can use random.choice to generate random indices without replacement
    # Please have a look at this link https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.choice.html for more details
    # Please follow above pseudo code for generating samples 
    
    selected_rows = np.random.choice(input_data.shape[0], 303, replace=False)
    replacing_rows = np.random.choice(len(selected_rows), 203, replace=True)
    random_column_idx = np.random.randint(3,13)
    selected_columns = np.random.choice(13, size=random_column_idx, replace=False)
    
    sample_data = input_data[selected_rows[:,None], selected_columns]
    target_of_sample_data = target_data[selected_rows]
    
    #Replicating data
    
    replicated_sample_data = sample_data[replacing_rows]
    target_of_replicated_sample_data = target_data[replacing_rows]
    
    #Concatenating data
    
    final_sample_data = np.vstack((sample_data, replicated_sample_data))
    final_target_data = np.vstack((target_of_sample_data.reshape(-1,1), target_of_replicated_sample_data.reshape(-1,1)))
    
    return final_sample_data, final_target_data, selected_rows, selected_columns
    

    # return sampled_input_data , sampled_target_data,selected_rows,selected_columns
    #note please return as lists

<font color='cyan'> <b> Grader function - 1 </b> </fongt>

In [6]:
def grader_samples(a,b,c,d):
    length = (len(a)==506  and len(b)==506)
    sampled = (len(a)-len(set([str(i) for i in a]))==203)
    #print(len(set([str(i) for i in a])))
    rows_length = (len(c)==303)
    column_length= (len(d)>=3)
    #print(length, sampled, rows_length, column_length)
    assert(length and sampled and rows_length and column_length)
    return True
a,b,c,d = generating_samples(x, y)
grader_samples(a,b,c,d)

True

*  <font color='blue'> <b>Create 30 samples </b>

![alt text](https://i.imgur.com/p8eZaWL.jpg)

In [7]:
# Use generating_samples function to create 30 samples 
# store these created samples in a list
list_input_data = []
list_output_data = []
list_selected_row = []
list_selected_columns = []

for i in range(0, 30):
    a, b, c, d = generating_samples(x, y)
    list_input_data.append(a)
    list_output_data.append(b)
    list_selected_row.append(c)
    list_selected_columns.append(d)

<font color='cyan'> <b>Grader function - 2 </b></font>

In [8]:
def grader_30(a):
    assert(len(a)==30 and len(a[0])==506)
    return True
grader_30(list_input_data)

True

<br>

<font color='red'><b>Step - 2 </b></font>

<font color='orange'><b>Flowchart for building tree</b></font>

![alt text](https://i.imgur.com/pcXfSmp.png)

*  <font color='blue'><b> Write code for building regression trees</b></font>

In [9]:
from sklearn import tree

def build_tree(list_input_data, list_output_data):

    list_of_all_models = []

    for i in range(0, len(list_input_data)):
        model = tree.DecisionTreeRegressor(max_depth = None)
        model.fit(list_input_data[i], list_output_data[i])

        list_of_all_models.append(model)
        
    return list_of_all_models

list_of_all_models = build_tree(list_input_data, list_output_data)

<font color='orange'><b>Flowchart for calculating MSE </b></font>

![alt text](https://i.imgur.com/sPEE618.png)

After getting predicted_y for each data point, we can use sklearns mean_squared_error to calculate the MSE between predicted_y and actual_y.

*  <font color='blue'><b> Write code for calculating MSE</b></font>

In [27]:
from sklearn.metrics import mean_squared_error

def calculate_mse(list_of_all_models, list_selected_columns):
    y_pred = []

    for i in range(len(x)):
        y_ = []
        for j in range(len(list_of_all_models)):
            y_.append(list_of_all_models[j].predict(x[i][list_selected_columns[j]].reshape(1,-1)))
        y_pred.append(np.average(y_))
        
    return mean_squared_error(y, y_pred)


print(calculate_mse(list_of_all_models, list_selected_columns))

12.616799211172102


<font color='blue'><b>Step - 3 </b></font>

<font color='orange'><b>Flowchart for calculating OOB score</b></font>

![alt text](https://i.imgur.com/95S5Mtm.png)

Now calculate the $OOB Score =  \frac{1}{506}\sum_{i=1}^{506}(y^{i} - y^{i}_{pred})^{2}$.

*  <font color='blue'><b> Write code for calculating OOB score </b></font>

In [21]:
import warnings
warnings.filterwarnings('ignore')

def calculate_oob(list_of_all_models, list_input_data, list_selected_row, list_selected_columns):
    #oob_score_list = []
    y_pred1 = []
    for i in range(len(x)):
        oob_list = []
        #print(i, x[i])
        for j in range(len(list_of_all_models)):
            if x[list_selected_columns[j]] not in list_input_data[j]:
                
                oob_list.append(list_of_all_models[j].predict(x[i][list_selected_columns[j]].reshape(1,-1)))

        y_pred1.append(np.median(np.asarray(oob_list)))
        
    return mean_squared_error(y, y_pred1)
    
print(calculate_oob(list_of_all_models, list_input_data, list_selected_row, list_selected_columns))

8.128093437262562


# <font color='blue'><b>Task 2</b></font>

In [22]:
train_mse = []
oob_score = []
#list_of_all_models_1 = []

list_input_data_2 =[]
list_output_data_2 =[]
list_selected_row_2 = []
list_selected_columns_2 =[]

for i in range(35):
    list_input_data_1 =[]
    list_output_data_1 =[]
    list_selected_row_1 = []
    list_selected_columns_1 =[]
    for j in range(30):
        a_1, b_1, c_1, d_1 = generating_samples(x, y)
#         grader_samples(a_1, b_1, c_1, d_1)

        list_input_data_1.append(a_1)
        list_output_data_1.append(b_1)
        list_selected_row_1.append(c_1)
        list_selected_columns_1.append(d_1)
        
    list_input_data_2.append(list_input_data_1)  
    list_output_data_2.append(list_output_data_1)  
    list_selected_row_2.append(list_selected_row_1)  
    list_selected_columns_2.append(list_selected_columns_1)  
#     grader_30(list_input_data_1)
    
for i in range(len(list_input_data_2)):
    
    list_of_all_models_1 = build_tree(list_input_data_2[i], list_output_data_2[i])

    train_mse.append(calculate_mse(list_of_all_models_1, list_selected_columns_2[i]))
    oob_score.append(calculate_oob(list_of_all_models_1, list_input_data_2[i], list_selected_row_2[i], list_selected_columns_2[i]))
    

print("Train : " , train_mse)
print("OOB : " , oob_score)

Train :  [11.773230691736563, 11.321653848954519, 11.919990732622114, 12.350751425207564, 12.619627951577108, 12.934890385905264, 11.87783407168136, 13.333172227827914, 11.984865337270477, 11.705516926884439, 11.797196538399913, 12.41229523224236, 11.94744762971876, 12.276780963199078, 12.591159108865764, 13.829899192041847, 12.779806148435725, 13.53844030563144, 11.575161600221783, 13.778107011180738, 12.267911582471417, 13.276873202519116, 12.384820133654523, 11.844973510890194, 11.993983695514869, 11.67511411783292, 11.107027139624828, 11.986777857756309, 12.499925288171706, 11.6938909758957, 11.81323464759308, 12.901217499086137, 12.463255956267446, 12.445207106607063, 11.728978508269337]
OOB :  [7.567981383124725, 6.820685420783925, 8.054685788592446, 8.359689732927094, 7.64150934564702, 8.948266545221514, 6.886443926716502, 9.446024324245943, 7.898840802324058, 6.876777092940272, 8.307768902690215, 8.283319421608905, 7.517937481262269, 8.21521166145147, 8.00169808699922, 10.98467

In [23]:
import math

sample_train_mean = np.mean(train_mse) 
sample_oob_mean = np.mean(oob_score)

sample_train_std = np.std(train_mse)
sample_oob_std = np.std(oob_score)

mse_ci_lower = sample_train_mean - 2 * (sample_train_std / math.sqrt(len(train_mse)))
mse_ci_upper = sample_train_mean + 2 * (sample_train_std / math.sqrt(len(train_mse)))

oob_ci_lower = sample_oob_mean - 2 * (sample_oob_std / math.sqrt(len(oob_score)))
oob_ci_upper = sample_oob_mean + 2 * (sample_oob_std / math.sqrt(len(oob_score)))

print("95% of the confidence interval of train_mse lies between : [{}, {}]".format(mse_ci_lower, mse_ci_upper))
print("95% of the confidence interval of oob_score lies between : [{}, {}]".format(oob_ci_lower, oob_ci_upper))

95% of the confidence interval of train_mse lies between : [12.073570324976135, 12.522487877981543]
95% of the confidence interval of oob_score lies between : [7.734148858657374, 8.381257814853178]


# <font color='blue'><b>Task 3</b></font>

<font color='orange'><b>Flowchart for Task 3</b></font>

<b>Hint: </b> We created 30 models by using 30 samples in TASK-1. Here, we need send query point "xq"  to 30 models and perform the regression on the output generated by 30 models.

![alt text](https://i.imgur.com/Y5cNhQk.png)

*  <font color='blue'><b> Write code for TASK 3 </b></font>

In [24]:
xq = [0.18, 20.0, 5.00, 0.0, 0.421, 5.60, 72.2, 7.95, 7.0, 30.0, 19.1, 372.13, 18.60]

pred_xq = []
for i in range(len(list_of_all_models)):
    pred_xq.append(list_of_all_models[i].predict(np.array(xq)[list_selected_columns[i]].reshape(1, -1)))
    
print("Predicted house value : ", np.average(pred_xq))

21.882777777777775


<br><br><br>

<font color='red'><b>Write observations for task 1, task 2, task 3 indetail</b></font>

In task1, doing bootstrap sampling looks easier than implementation, but with the help of the above notes I've learnt how to do it. Once its done with the help of notes, its easier to calculate mse and oob score.

In task2, iterating the task1 and finding the confidence interval by considering the mse and oob score as samples.

In task3, finding the house value based by sending the various other numerical parameter to the trained model and got the predicted value based on all the ensemble models and aggregating them together to achieve the final result.